service: excellApp-api

plugins:
  - serverless-offline # Allow local hosting via `serverless offline`

provider:
  name: aws # this has to be hardcoded
  stage: dev
  region: us-east-1
  profile: personal
  runtime: nodejs14.x

custom:
  serverless-offline:
    allowCache: false

functions:
  read:
    name: excellApp-read-dev
    handler: read/index.handler
    description: API function to read
    memorySize: 128
    timeout: 28
    events:
      - http:
          path: backend/read
          method: post
          cors: true